const ShopActionTypes = {
  FETCH_COLLECTİONS_START: "FETCH_COLLECTİONS_START",
  FETCH_COLLECTİONS_SUCCESS: "FETCH_COLLECTİONS_SUCCESS",
  FETCH_COLLECTİONS_FAILURE: "FETCH_COLLECTİONS_FAILURE",
};

export default ShopActionTypes;
